### ISSUE TITLE
Ip blocked. To many polls

### ISSUE THREAD

**Issue by magtimmermans** [geertmeersman/youfone#55]
I had added 3 devices to the integration and now I am blocked als probably to many polls.

**Comment by geertmeersman** [comment]
Hi Marcel, did this happen with the last release?
I have no idea which limit they set at Youfone... I can increase the update frequency, will check it tomorrow.

**Comment by magtimmermans** [comment]
Hi, yes. With the latest release. I think they are very strict for some reason. I am not sure if it is only with login or also retrieving info.

**Comment by geertmeersman** [comment]
And how can you get  the IP ban released?

**Comment by magtimmermans** [comment]
I am not sure.  I have sent them an email.

**Comment by silvanverschuur** [comment]
@magtimmermans Any news on this? I think I'm facing the same issue. I've used an other integration for months without any problems. Suddenly it doesn't work anymore. I've tried to install this integration but is gives an error when I try to add my account.

**Comment by magtimmermans** [comment]
Hi, yes the have contacted me last Monday and it seems to work again. According to the person that talked with me this mechanism works for protecting there site. He didn't mention details but after x time within x time it blocks yor ip adres. After some time it will release it again. If you try again many time the block will be longer etc.

**Comment by silvanverschuur** [comment]
@magtimmermans Thanks for the update. I'm facing this issue for about a week now....hope they will release my IP soon.
@geertmeersman For this reason I would suggest to add some kind of polling interval setting to prevent these IP blocks. It's fine for me if the data is updated a couple of times a day.

**Comment by magtimmermans** [comment]
For me the suggestion of @silvanverschuur works also.

**Comment by geertmeersman** [comment]
Will do, I'm currently on holidays but I'll try to find some time 😀
You can always update it yourself in the const.py file, I called the variable UPDATE_INTERVAL if I'm not wrong

**Comment by magtimmermans** [comment]
Well the login doesn't work at all at the moment even thought the block is removed. So enjoy first your holiday and after that we will try again.

**Comment by marceldeklerk** [comment]
Same problem here, it seems. 
I have 3 Youfone subscriptions, it suddenly stopped working. I have not found any indication of an ip block in the logs, though it is a plausable theory. I will disable the integration for some time, to see if i get unblocked at some point.

**Comment by geertmeersman** [comment]
Hi, can you test with the new release? Thx

**Comment by geertmeersman** [comment]
I have changed the update interval to 1 hour (instead of 15mins)

**Comment by geertmeersman** [comment]
Closing as it "seems" to be solved.

**Comment by magtimmermans** [comment]
am testing it now a few days and it seems working.

**Comment by geertmeersman** [comment]
I have added in the 0.4.4 release some random sleeps, hoping this will let the requests pass
