### ISSUE TITLE
Not working. Ip temp blocked.

### ISSUE THREAD

**Issue by VanFlipsen** [geertmeersman/youfone#86]
The integration has not been working for a while now.  I think since a last update of home assistant.  If I keep the integration active, my IP at youfone is blocked.  After a while (maybe a day) of keeping the integration disabled, I can connect to my.youfone.nl again, but the integration does not work and I get the log message below.  I can't see if this is related to the problem. 

I just got an IP ban from youfone after using the integration. 

```
Logger: homeassistant.util.async_
Source: util/async_.py:140
First occurred: 17:57:16 (4 occurrences)
Last logged: 17:58:10

Detected blocking call to sleep inside the event loop by custom integration 'youfone' at custom_components/youfone/__init__.py, line 46: time.sleep(random.uniform(1, 10)), please create a bug report at https://github.com/geertmeersman/youfone/issues

```

**Comment by geertmeersman** [comment]
Hi, I indeed also have the issue since a couple of days, but no idea what I can do to solve it. It is probably their ddos protection, Do you also have multiple accounts configured?

**Comment by VanFlipsen** [comment]
I have configured 2 accounts.  1 has been disabled for a while.
 Since yesterday there is no connection possible with my.youfone.nl.  If the connection can be made again, I will report back.

**Comment by geertmeersman** [comment]
once my IP is unblocked, I will try to narrow down the integration, like making the poll  of youcoins, invoices etc... optional, which will reduce  the calls  to the website. Their  DDOS system is quite quicly triggered

**Comment by VanFlipsen** [comment]
I can connect with Youfone again. Wil not try to enable the integration yet

**Comment by geertmeersman** [comment]
I think / hope that my workaround fixes it, let's give it a try :-)

**Comment by geertmeersman** [comment]
https://github.com/geertmeersman/youfone/releases/tag/v0.5.4

**Comment by VanFlipsen** [comment]
It works again and I now have 1 account enabled to try.  

Could it be that if I restart the system many times in one day, the integration logs in to Youfone too often.  I'm curious about that.

**Comment by geertmeersman** [comment]
Yes sure it could "log in" too often, but  I think it should be ok now with my fix, even if you restart it "often".
As long as it's not every minute :-)

But again, I don't know how many requests  they allow and in which period of time...

**Comment by geertmeersman** [comment]
I activated it for 2 accounts, so let's monitor on all sides

**Comment by SpeedlimitsB** [comment]
It works for me . You can also try to proxy your HA to make it work of you are bannend .
